version: v0.0.test.{build}

only_commits:
  message: /build/
    
pull_requests:
  do_not_increment_build_number: true
  
build:
  verbosity: normal

deploy:
  provider: GitHub
  tag: test tag
  release: test name
  description: test release
  auth_token:
    secure: 6bf257a9fcd270a31315204436678b80f97d0d41
  prerelease: true
  force_update: true
  on:
    configuration: release